name: Compile VEX Code with PROS

# Controls when the action will run. 
on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup GCC
      run: |
        sudo apt-get install -y gcc-arm-none-eabi
    - name: Install PROS dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user https://github.com/purduesigbots/pros-cli/releases/download/3.1.4/pros_cli_v5-3.1.4-py3-none-any.whl
    - name: Clean and compile PROS project
      run: |
        export PATH=/home/runner/.local/bin:$PATH
        cd 90819A
        prosv5 make all
